### ISSUE TITLE
errors ( from a noob :P ) 

### ISSUE THREAD

**Issue by pedromgapt** [johanhermansson/letterboxd-exporter#1]
Error: Cannot find module 'promise-crawler'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/letterboxd-export.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! letterboxed2taste@0.0.1 letterboxd-export: `node letterboxd-export.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the letterboxed2taste@0.0.1 letterboxd-export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2019-12-31T16_07_11_722Z-debug.log
exit status 1


https://snipboard.io/NUXkPY.jpg

**Comment by johanhermansson** [comment]
You need to run `npm install` within the folder to install the packages

You probably also want to set your current `TASTE_DEFAULT_STATUS` to `true` so you don't update ratings for all of your old ratings. Then you could of course update your `movies.json` manually for your latest ratings so they are imported into Taste.io before you run the importer. Just change `tasteStatus: true` to `tasteStatus: false` for those movies :)

**Comment by pedromgapt** [comment]
was not really an issue i guess, was a problem from someone who can´t code and needs to rely on this type of websites 📦 its working! :)
the only "error" i fund is not really an error, it´s movies with the same name. but that can be fixed on a few mins.
again, thank you for this! =)

**Comment by pedromgapt** [comment]
"{ HTTPError: Response code 429 (Too Many Requests)
    at EventEmitter.emitter.on (/home/runner/node_modules/got/dist/source/as-promise.js:108:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError' }"

taste.io really doens´t like this kind of stuff hehe

**Comment by johanhermansson** [comment]
Hehe Maybe I should make it slower.

Best regards,
Johan

**Comment by pedromgapt** [comment]
well, you know there´s a good thing that come out of it. when it stops and u run again, it puts the missing movies in a row at the start of the script every single time, so it makes a "List" that becomes bigger and at the end you just need to copy paste them instead of going over though all the script  ( if you run when all is added, it makes that list )   . also the problem might be me; the amount of ratings. he lets rate about 300 in a row before stooping. i got 4350.
it´s rating perfectly ( the previous version for some reason would rate amazing, movies that sucked lol ) . so .. kudus to you! thank you for this. i was gonna start using "Must app" now i wont :P 

https://www.taste.io/users/pedropt feel free to add =)
